# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6c52e05c5d8be46e2a2eba5d564fa3e3a441463fda1ff5ba2be1c6a0bb5317296340891bd90dbbe99629f89db04f00e8f60a36e43668cc7de3d7463933bdf39

test:
  secret_key_base: 3ee2d08bf29d03e05288516a4bbd2d0d33ed5a7e53dde36b66d31ca61c134e5c8339b6ab03fd362d2e73696e213d5dfe10a5c6506fa8d6db6a30726f6098f80b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
